apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: patientservice
spec:
  template:
    metadata:
      labels:
        app: patientservice
    spec:
      containers:
        - name: patientservice
          image: patientservice
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: patientservice
spec:
  type: NodePort
  ports:
    - nodePort: 31317
      port: 8080
      protocol: TCP
  selector:
    app: patientservice