apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: patient-service
spec:
  template:
    metadata:
      labels:
        app: patientservice
    spec:
      containers:
        - name: patient-service
          image: patient-service
          imagePullPolicy: "Never"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: NodePort
  ports:
    - nodePort: 31312
      port: 80
      protocol: TCP
  selector:
    app: patient-service