apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-patient
spec:
  template:
    metadata:
      labels:
        app: postgres-patient
    spec:
      containers:
        - name: postgres-patient
          image: postgres:9.6.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: patient
            - name: POSTGRES_USER
              value: sarah
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-patient
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-patient